### ISSUE TITLE
Memory error after powerup init

### ISSUE THREAD

**Issue by Lukaspor** [KawaiiKraken/GLaDOS-GPT#14]
```
announce.powerup.init()
loading stt_model...
Traceback (most recent call last):
  File "/home/pi/GLaDOS-GPT/./glados.py", line 394, in <module>
    main()
  File "/home/pi/GLaDOS-GPT/./glados.py", line 364, in main
    stt_model = whisper.load_model(whisper_model + ".en")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/whisper/__init__.py", line 133, in load_model
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/whisper/__init__.py", line 61, in _download
    model_bytes = f.read()
                  ^^^^^^^^
MemoryError
```
Getting this error after power up init announcement.

**Comment by Lukaspor** [comment]
Fairly certain this had to do with me initially trying to run this on a raspberry pi. Realizing now that it takes a good bit of memory to run. Ended up using WSL ubuntu on my main PC with some tweaking.
